version: 0.2

phases:
  build:
    commands:
      - mvn package -DskipTests
      - mv target/classes/* .
      - rm -rf target src buildspec.yml pom.xml
      - aws cloudformation package --template-file sam.yaml --output-template-file output-sam.json

artifacts:
  files:
    - output-sam.yaml
    - target/serverless-spring-example-1.0-SNAPSHOT.jar
