AWSTemplateFormatVersion: '2010-09-09'
Description: Example Pet Store API written with spring with the aws-serverless-java-container
  library
Outputs:
  SpringPetStoreApi:
    Description: URL for application
    Export:
      Name: SpringPetStoreApi
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/pets
Resources:
  PetStoreFunction:
    Properties:
      CodeUri: s3://s3-code-pipeline-pets/a3ea5e92b4ee151bac05ee41f9311e3a
      Events:
        GetResource:
          Properties:
            Method: any
            Path: /{proxy+}
          Type: Api
      Handler: com.amazonaws.serverless.sample.spring.LambdaHandler::handleRequest
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Runtime: java8
      Timeout: 20
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
